name: Build Java File

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: test

    steps:
    - uses: actions/checkout@v3

    - name: Validate the syntax
      run: mvn validate

    - name: Do a clean Package and install
      run: mvn clean install
      
    - name: List the build artifact
      run: ls target/
